# Generated by Django 5.0.6 on 2024-06-26 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('location', models.TextField(choices=[('greece', 'GREECE'), ('spain', 'SPAIN'), ('italy', 'ITALY'), ('england', 'ENGLAND')], default='england', max_length=7)),
                ('theme', models.CharField(choices=[('beach', 'BEACH'), ('barn', 'BARN'), ('classic', 'CLASSIC'), ('rustic', 'RUSTIC'), ('fairytale', 'FAIRYTALE')], default='classic', max_length=9)),
                ('image', models.ImageField(blank=True, default='../default_post_a0da7q', upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
