# Generated by Django 3.2.4 on 2024-08-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20240806_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.TextField(choices=[('greece', 'GREECE'), ('spain', 'SPAIN'), ('italy', 'ITALY'), ('england', 'ENGLAND')], default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='theme',
            field=models.CharField(choices=[('beach', 'BEACH'), ('barn', 'BARN'), ('classic', 'CLASSIC'), ('rustic', 'RUSTIC'), ('fairytale', 'FAIRYTALE')], default='', max_length=9),
        ),
    ]
